// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5XwS32dQmb5gUJr4QwFmsMXrISF80zK4',
    appId: '1:860712435761:web:56d5729b8ec8697443d510',
    messagingSenderId: '860712435761',
    projectId: 'olympia-rev-62bff',
    authDomain: 'olympia-rev-62bff.firebaseapp.com',
    storageBucket: 'olympia-rev-62bff.appspot.com',
    measurementId: 'G-1VPZ3QLTNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsTbZnfMeR-NP0mOvVrj1Wt8TARqkz5PI',
    appId: '1:860712435761:android:27148b809039accf43d510',
    messagingSenderId: '860712435761',
    projectId: 'olympia-rev-62bff',
    storageBucket: 'olympia-rev-62bff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjdhByfcFpjKhVumHhcY8CQUa8fM61fq8',
    appId: '1:860712435761:ios:d42a37079c65682743d510',
    messagingSenderId: '860712435761',
    projectId: 'olympia-rev-62bff',
    storageBucket: 'olympia-rev-62bff.appspot.com',
    iosBundleId: 'com.example.olympiaRev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjdhByfcFpjKhVumHhcY8CQUa8fM61fq8',
    appId: '1:860712435761:ios:d42a37079c65682743d510',
    messagingSenderId: '860712435761',
    projectId: 'olympia-rev-62bff',
    storageBucket: 'olympia-rev-62bff.appspot.com',
    iosBundleId: 'com.example.olympiaRev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5XwS32dQmb5gUJr4QwFmsMXrISF80zK4',
    appId: '1:860712435761:web:f7086a6c102d610843d510',
    messagingSenderId: '860712435761',
    projectId: 'olympia-rev-62bff',
    authDomain: 'olympia-rev-62bff.firebaseapp.com',
    storageBucket: 'olympia-rev-62bff.appspot.com',
    measurementId: 'G-FLDHMM8ZEL',
  );
}
